# ============================================================
# pipeline/summarizer.py — AI Summary Generator
# ============================================================
# Generates plain English 2-3 line summaries for papers.
# Uses Gemini Flash (cheap + fast) via core/llm.py.
#
# KEY PRINCIPLE: Each paper is summarised ONCE and stored.
# 10,000 users reading the same paper = 1 API call total.
#
# Cost estimate:
#   Gemini Flash: $0.075 per 1M input tokens
#   Average paper: ~200 tokens input, ~60 tokens output
#   50 papers per fetch: ~0.001 USD (less than 0.1 cent)
#   Running every 5 min: ~$0.30/day maximum
# ============================================================

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import asyncio
import time
from datetime import datetime

from config import DEBUG, ACTIVE_LLM
from core.llm import call_llm
from scrapers.arxiv import Paper


# ============================================================
# SETTINGS
# ============================================================

# How many papers to summarise in one batch before pausing
BATCH_SIZE = 5

# Seconds to wait between batches (avoid rate limiting)
BATCH_DELAY_SECONDS = 2

# Seconds to wait between individual calls within a batch
CALL_DELAY_SECONDS = 0.5

# Max characters of abstract to send to LLM (saves tokens)
MAX_ABSTRACT_CHARS = 800


# ============================================================
# SYSTEM PROMPT
# ============================================================
# This is the "personality" instruction we give to the AI.
# It shapes how every summary is written.
# Adjust this if you want a different tone or style.

SUMMARY_SYSTEM = """You are an AI/ML research explainer for PaperLens.
Your job: explain research papers in plain English for software engineers.

Rules:
- Write EXACTLY 2-3 sentences. No more, no less.
- Use plain English. Avoid jargon.
- Never start with "The paper", "The authors", or "This paper".
- Focus on: what problem, how solved, why it matters.
- Be specific about numbers/results when available.
- No bullet points. Flowing prose only."""


# ============================================================
# MAIN FUNCTION — summarize_batch()
# ============================================================

async def summarize_batch(papers: list[Paper]) -> list[Paper]:
    """
    Generate summaries for a batch of papers.
    Skips papers that already have summaries.

    Parameters:
        papers → list of processed Paper objects

    Returns:
        Same list with .summary field filled in for each paper
    """
    # Filter papers that need summaries
    needs_summary = [p for p in papers if not p.summary]
    already_done = len(papers) - len(needs_summary)

    if not needs_summary:
        if DEBUG:
            print("[summarizer] All papers already have summaries")
        return papers

    print(f"\n✍️  Summarizing {len(needs_summary)} papers "
          f"({already_done} already done)...")

    # Estimate cost before running
    cost = estimate_cost(needs_summary)
    print(f"   Est. cost: ${cost['estimated_usd']:.4f} USD")

    # Process in small batches
    start_time = time.time()
    success_count = 0
    fail_count = 0

    for i in range(0, len(needs_summary), BATCH_SIZE):
        batch = needs_summary[i:i + BATCH_SIZE]
        batch_num = (i // BATCH_SIZE) + 1
        total_batches = (len(needs_summary) + BATCH_SIZE - 1) // BATCH_SIZE

        if DEBUG:
            print(f"\n[summarizer] Batch {batch_num}/{total_batches}")

        # Process each paper in this batch
        for paper in batch:
            success = await _summarize_one(paper)
            if success:
                success_count += 1
            else:
                fail_count += 1

            # Small delay between individual calls
            await asyncio.sleep(CALL_DELAY_SECONDS)

        # Pause between batches (rate limit protection)
        if i + BATCH_SIZE < len(needs_summary):
            if DEBUG:
                print(f"[summarizer] Batch done. Waiting {BATCH_DELAY_SECONDS}s...")
            await asyncio.sleep(BATCH_DELAY_SECONDS)

    elapsed = time.time() - start_time
    print(f"   ✅ Done: {success_count} summaries generated "
          f"({fail_count} fallbacks) in {elapsed:.1f}s\n")

    return papers


# ============================================================
# SUMMARISE ONE PAPER
# ============================================================

async def _summarize_one(paper: Paper) -> bool:
    """
    Generate summary for a single paper.
    Updates paper.summary in place.

    Returns:
        True  → summary generated by AI
        False → fallback summary used (AI failed)
    """
    try:
        # Build the prompt
        prompt = _build_prompt(paper)

        if DEBUG:
            print(f"  [summarizer] '{paper.title[:50]}...'")

        # Call LLM
        summary = await call_llm(
            prompt=prompt,
            system=SUMMARY_SYSTEM,
            temperature=0.2,    # low temperature = consistent, focused output
        )

        # Validate the response
        if _is_valid_summary(summary):
            paper.summary = _clean_summary(summary)
            if DEBUG:
                print(f"  [summarizer] ✅ '{paper.summary[:80]}...'")
            return True
        else:
            # LLM returned an error or garbage
            paper.summary = _fallback_summary(paper)
            if DEBUG:
                print(f"  [summarizer] ⚠️  Used fallback summary")
            return False

    except Exception as e:
        print(f"  [summarizer] ❌ Error for '{paper.title[:40]}': {e}")
        paper.summary = _fallback_summary(paper)
        return False


# ============================================================
# BUILD PROMPT
# ============================================================

def _build_prompt(paper: Paper) -> str:
    """
    Build the summary prompt for a paper.
    Trims abstract to save tokens.
    """
    # Trim abstract to save tokens
    abstract = paper.abstract[:MAX_ABSTRACT_CHARS]
    if len(paper.abstract) > MAX_ABSTRACT_CHARS:
        abstract += "..."

    # Format authors (max 3)
    if paper.authors:
        authors_str = ", ".join(paper.authors[:3])
        if len(paper.authors) > 3:
            authors_str += f" et al."
    else:
        authors_str = "Unknown authors"

    prompt = f"""Summarize this research paper in 2-3 sentences.

Title: {paper.title}
Authors: {authors_str}
Source: {paper.source.upper()}
Abstract: {abstract}

Write the summary now:"""

    return prompt


# ============================================================
# VALIDATION & CLEANING
# ============================================================

def _is_valid_summary(text: str) -> bool:
    """
    Check if the LLM returned a valid summary.
    Rejects error messages, empty responses, one-word answers.
    """
    if not text:
        return False

    # Reject error messages from llm.py
    if text.startswith("Error:"):
        return False

    # Reject if too short (less than 50 characters)
    if len(text.strip()) < 50:
        return False

    # Reject if too long (more than 500 characters = probably wrong format)
    if len(text.strip()) > 500:
        return False

    return True


def _clean_summary(text: str) -> str:
    """
    Clean up the AI-generated summary.
    - Remove surrounding quotes if any
    - Fix whitespace
    - Ensure it ends with a period
    """
    # Remove surrounding quotes
    text = text.strip().strip('"').strip("'").strip()

    # Fix whitespace
    text = ' '.join(text.split())

    # Ensure ends with punctuation
    if text and text[-1] not in '.!?':
        text += '.'

    return text


def _fallback_summary(paper: Paper) -> str:
    """
    Generate a basic summary when AI fails.
    Uses the first 2 sentences of the abstract.
    Better than showing nothing to the user.
    """
    if not paper.abstract:
        return f"Research paper: {paper.title}"

    # Split into sentences
    import re
    sentences = re.split(r'(?<=[.!?])\s+', paper.abstract.strip())

    # Take first 2 sentences
    if len(sentences) >= 2:
        fallback = ' '.join(sentences[:2])
    else:
        fallback = paper.abstract[:200]

    # Truncate if too long
    if len(fallback) > 300:
        fallback = fallback[:297] + "..."

    return fallback


# ============================================================
# COST ESTIMATION
# ============================================================

def estimate_cost(papers: list[Paper]) -> dict:
    """
    Estimate Gemini API cost for summarising a batch of papers.
    Helps you understand costs before running.

    Gemini Flash pricing (as of 2025):
        Input:  $0.075 per 1M tokens
        Output: $0.30  per 1M tokens

    Typical paper:
        Input:  ~250 tokens (title + abstract + prompt template)
        Output: ~60  tokens (2-3 sentences)
    """
    # Estimate tokens per paper
    avg_input_tokens = 250
    avg_output_tokens = 60

    total_input  = len(papers) * avg_input_tokens
    total_output = len(papers) * avg_output_tokens

    # Gemini Flash pricing
    cost_input  = (total_input  / 1_000_000) * 0.075
    cost_output = (total_output / 1_000_000) * 0.30
    total_cost  = cost_input + cost_output

    return {
        "paper_count":      len(papers),
        "input_tokens":     total_input,
        "output_tokens":    total_output,
        "cost_input_usd":   round(cost_input,  6),
        "cost_output_usd":  round(cost_output, 6),
        "estimated_usd":    round(total_cost,  6),
        "model":            ACTIVE_LLM,
    }


# ============================================================
# TEST — run this file directly
# Command: python pipeline/summarizer.py
# ============================================================

async def _test():
    print(f"\n{'='*55}")
    print(f"  Testing Pipeline Summarizer")
    print(f"{'='*55}\n")

    # Create test papers
    from datetime import timezone
    now = datetime.now(timezone.utc)

    test_papers = [
        Paper(
            id="1706.03762",
            title="Attention Is All You Need",
            abstract="The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train.",
            authors=["Ashish Vaswani", "Noam Shazeer", "Niki Parmar"],
            url="https://arxiv.org/abs/1706.03762",
            published_at=now,
            source="arxiv",
        ),
        Paper(
            id="2301.00001",
            title="Scaling Language Model Reasoning with Chain-of-Thought Distillation",
            abstract="We propose a new distillation framework that transfers long chain-of-thought reasoning from large language models to smaller ones without quality loss. Our step-level supervision forces the student model to match every intermediate reasoning step from the teacher. The 7B student model matches the 70B teacher on GSM8K at 9.8 times faster inference speed.",
            authors=["Wei Chen", "Priya Sharma", "Lucas Dubois"],
            url="https://arxiv.org/abs/2301.00001",
            published_at=now,
            source="arxiv",
        ),
    ]

    # Test cost estimation
    print("Cost estimation:")
    cost = estimate_cost(test_papers)
    print(f"  Papers       : {cost['paper_count']}")
    print(f"  Input tokens : ~{cost['input_tokens']:,}")
    print(f"  Output tokens: ~{cost['output_tokens']:,}")
    print(f"  Est. cost    : ${cost['estimated_usd']:.6f} USD")
    print(f"  Model        : {cost['model']}\n")

    # Test summarization
    print("Generating summaries...")
    papers_with_summaries = await summarize_batch(test_papers)

    print("\nResults:")
    for p in papers_with_summaries:
        print(f"\n  [{p.id}]")
        print(f"  Title  : {p.title[:60]}")
        print(f"  Summary: {p.summary}")

    # Test fallback
    print("\nTesting fallback summary...")
    empty_paper = Paper(
        id="test-fallback",
        title="Test Paper",
        abstract="First sentence of abstract. Second sentence here. Third sentence is longer and goes on a bit more.",
        authors=[],
        url="https://arxiv.org/abs/test",
        published_at=now,
        source="arxiv",
    )
    fallback = _fallback_summary(empty_paper)
    print(f"  Fallback: {fallback}")

    print(f"\n{'='*55}")
    print(f"  ✅ Summarizer test complete!")
    print(f"{'='*55}\n")


if __name__ == "__main__":
    asyncio.run(_test())
